# Generated by Django 5.2 on 2025-04-14 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('full', models.CharField(max_length=21, validators=[django.core.validators.MinLengthValidator(19)])),
            ],
        ),
    ]
