# Generated by Django 5.2 on 2025-04-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
