# Generated by Django 5.2 on 2025-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_alter_trip_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
