# Generated by Django 5.2 on 2025-04-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0004_trip_done_alter_trip_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dropOff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_point', to='nav.point'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickUp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_point', to='nav.point'),
        ),
    ]
