# Generated by Django 5.2 on 2025-06-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0005_alter_trip_dropoff_alter_trip_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='booked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
