# Generated by Django 5.2 on 2025-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0006_alter_trip_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='nicknames',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
