# Generated by Django 5.2 on 2025-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0007_point_nicknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='eta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
