# Generated by Django 5.2 on 2025-06-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0008_trip_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
