# Generated by Django 5.2 on 2025-07-01 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0009_trip_canceled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('mileage', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('disabled', models.BooleanField(default=False)),
                ('lastInspected', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehivle_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
