# Generated by Django 5.2 on 2025-07-02 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0011_alter_vehicle_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_vehicle', to='nav.vehicle'),
        ),
    ]
