# Generated by Django 5.2 on 2025-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0013_trip_rideid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
